// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKz5vYrutSeNG0V536J8T_nfkielZGiKQ',
    appId: '1:754901539952:web:0ff8a0097c165fe6eb28b5',
    messagingSenderId: '754901539952',
    projectId: 'flutter-to-do-list-app-3782197',
    authDomain: 'flutter-to-do-list-app-3782197.firebaseapp.com',
    storageBucket: 'flutter-to-do-list-app-3782197.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUzstrB9Sx8_p08sqkkNwwmo4xbvpCaiY',
    appId: '1:754901539952:android:24735e950d493c7beb28b5',
    messagingSenderId: '754901539952',
    projectId: 'flutter-to-do-list-app-3782197',
    storageBucket: 'flutter-to-do-list-app-3782197.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQF3dreSGMITrXSkfu_J-ZAEy4Z8NpVYk',
    appId: '1:754901539952:ios:f8038ca49e057d59eb28b5',
    messagingSenderId: '754901539952',
    projectId: 'flutter-to-do-list-app-3782197',
    storageBucket: 'flutter-to-do-list-app-3782197.appspot.com',
    iosBundleId: 'com.example.flutterTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQF3dreSGMITrXSkfu_J-ZAEy4Z8NpVYk',
    appId: '1:754901539952:ios:f8038ca49e057d59eb28b5',
    messagingSenderId: '754901539952',
    projectId: 'flutter-to-do-list-app-3782197',
    storageBucket: 'flutter-to-do-list-app-3782197.appspot.com',
    iosBundleId: 'com.example.flutterTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKz5vYrutSeNG0V536J8T_nfkielZGiKQ',
    appId: '1:754901539952:web:64546cc895af5dd1eb28b5',
    messagingSenderId: '754901539952',
    projectId: 'flutter-to-do-list-app-3782197',
    authDomain: 'flutter-to-do-list-app-3782197.firebaseapp.com',
    storageBucket: 'flutter-to-do-list-app-3782197.appspot.com',
  );
}
